AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template for Python Lambda function with dependencies

Metadata:
  BuildMethod: python3.9
  PythonRequirements:
    - requirements.txt

Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: 'FUNCTION_NAME'
      CodeUri: 'LOCATION'/
      Handler: app.lambda_handler
      Runtime: python3.9
      MemorySize: 128
      Timeout: 30
      Policies:
        - DynamoDBCrudPolicy:
            TableName: 'TABLE_NAME'

  SendEmailsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: 'FUNCTION_NAME'
      CodeUri: 'LOCATION'
      Handler: 'HANDLER'
      Runtime: python3.9
      MemorySize: 128
      Timeout: 30
      Policies:
        - AmazonS3ReadOnlyAccess
        - AmazonSESFullAccess

  BlogPostsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: 'TABLE_NAME'
      AttributeDefinitions:
        - AttributeName: Title
          AttributeType: S
      KeySchema:
        - AttributeName: Title
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      
  ExcelSheetsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 'BUCKET_NAME'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true

