AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template for Python Lambda function with dependencies

Metadata:
  BuildMethod: python3.9
  PythonRequirements:
    - requirements.txt

Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Load_Blogs_DDB
      CodeUri: get_blogs/
      Handler: app.lambda_handler
      Runtime: python3.9
      MemorySize: 128
      Timeout: 30
      Policies:
        - DynamoDBCrudPolicy:
            TableName: BlogPosts

  SendEmailsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Send_Emails_Content_Drip
      CodeUri: email_content/
      Handler: app.send_emails
      Runtime: python3.9
      MemorySize: 128
      Timeout: 30
      Policies:
        - AmazonS3ReadOnlyAccess
        - AmazonSESFullAccess

  BlogPostsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: BlogPosts
      AttributeDefinitions:
        - AttributeName: Title
          AttributeType: S
      KeySchema:
        - AttributeName: Title
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      
  ExcelSheetsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: customer-drip-inbound
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true

