AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template for Python Lambda function with dependencies

Metadata:
  BuildMethod: python3.10
  PythonRequirements:
    - requirements.txt

Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Load_Blogs_DDB
      CodeUri: get_blogs/
      Handler: app.lambda_handler
      Runtime: python3.9
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          MY_VAR: "my-value"
      Policies:
        - DynamoDBCrudPolicy:
            TableName: BlogPosts

  BlogPostsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: BlogPosts
      AttributeDefinitions:
        - AttributeName: Title
          AttributeType: S
      KeySchema:
        - AttributeName: Title
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
